### Reference
https://www.scipy-lectures.org/intro/

In [1]:
import numpy as np
import scipy.integrate

#### Exercise: Perform integration of y = x**2

<img src = "Pic_data/Integration_1.png" width = 500>

## Solution
<img src = "Pic_data/Integration_2.png" width = 200>

#### In this Exercise we will perform Integration using approximation method (assume we dont know the real equation)

In [2]:
# สร้างค่า x ออกมาก่อน
x, dx = np.linspace(1, 10, 10, retstep=True)
x

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [64]:
dx

1.0

In [65]:
# y = e^x
y = x ** 2
y

array([  1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100.])

##### Simplified calculation of Area under curve (using piecewise calculation) or Riemann sum

การคำนวณพื้นที่แบบพื้นฐานที่สุดคือการเอาค่านั้นๆ เสมือนคำนวณ แยกกัน ตามกราฟแท่ง ยิ่งซอยย่อย ยิ่งแม่น

<img src = "pic_data/riemann_1.png" width = 300>

In [66]:
# เสมือนเอาแท่งๆ มาคูณกัน
AOC_basic = np.sum(y)*dx
AOC_basic

385.0

In [78]:
Error_basic = (AOC_basic - 333) / 333 * 100 # in percentage
Error_basic

15.615615615615615

##### Integrate along the given axis using the composite trapezoidal rule.

การคำนวณพื้นที่ระหว่างจุดของ trapezoid ใช้ Linear line ต่อระหว่างจุด

<img src = "pic_data/trapezoid_1.png" width = 300>


สามารถ approximate พื้นที่ใต้กราฟได้ดีกว่าวิธี piecewise

<img src = "pic_data/trapezoid.png" width = 300>



In [75]:
# What is Trapezoidal rule --> https://en.wikipedia.org/wiki/Trapezoidal_rule
# Reference for scipy --> https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.trapz.html

AOC_trapz = scipy.integrate.trapz(y, x)
AOC_trapz

334.5

In [77]:
Error_trapz = (AOC_trapz - 333) / 333 * 100 # in percentage
Error_trapz

0.45045045045045046

In [69]:
# Using Cumulative integration (ของแถมที่ scipy ทำไว้ให้)
# https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.cumtrapz.html#scipy.integrate.cumtrapz
AOC_trap_cum = scipy.integrate.cumtrapz(y, x, initial = 0)
AOC_trap_cum

array([  0. ,   2.5,   9. ,  21.5,  42. ,  72.5, 115. , 171.5, 244. ,
       334.5])

##### Integrate y(x) using samples along the given axis and the composite Simpson’s rule

การคำนวณพื้นที่ระหว่างจุดของ Simpson ใช้ Quadratic Interpolation line ต่อระหว่างจุด

<img src = "pic_data/simpson_1.png" width = 300>

สามารถ approximate พื้นที่ใต้กราฟได้ดีกว่าวิธี trapezoidal (ในกรณีส่วนมากถ้าการซอยย่อย ทำได้ดี ไม่งั้นอาจมี error ได้)

<img src = "pic_data/simpson_2.gif" width = 300>

In [80]:
# What is Simpson's rule --> https://en.wikipedia.org/wiki/Simpson%27s_rule
# Reference for scipy --> https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.simps.html
AOC_simps = scipy.integrate.simps(y, x)
AOC_simps

333.16666666666663

In [81]:
Error_simps = (AOC_simps - 333) / 333 * 100 # in percentage
Error_simps

0.050050050050038666